compatibility_date = "2024-09-30"
compatibility_flags = [ "nodejs_compat" ]

name = "flipthecoin-app"

main = ".output/server/index.mjs"

assets = { directory = ".output/public", binding = "ASSETS" }

[build]
command = "pnpm build"

[[kv_namespaces]]
binding = "flipthecoin_emails_list"
id = "a456c36d4e14411a8a8a9f6c8d3ff224"

[[kv_namespaces]]
binding = "flipthecoin-app-flipthecoin_emails_list_local"
id = "84542cf8ed754a35a8cfbcdd32aa9d7e"

[[d1_databases]]
binding = "cf_d1_flipthecoin_content"
database_name = "cf_d1_flipthecoin_content"
database_id = "742ff927-04aa-4c68-9ff9-6e45833c3216"

[observability]
enabled = true
